
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Drawer from "@/components/Drawer";
import GlobalProvider from "./GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "InvoiceApp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex bg-[#F8F8FB] `}>
        <GlobalProvider>
        <Sidebar/>
        <Drawer/>
        {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
